POST http://localhost:5000/api/client/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5YzhkODk4MjFkYWI3OWRkZDU4MmQiLCJlbWFpbCI6InJ1bG5vbmphQGFrLnNsZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA4NjQ5NTEsImV4cCI6MTczMDg2ODU1MX0.twhCVe6Ye5-3Umh49nZhTz1YXf0T_bmBZc24FHgAVcg

{
    "name":"lifetek3", "redirectUri":"https://facebook.com" ,"scope":"admin", "grantTypes": "authorization_code"
}

#####################
POST http://localhost:5000/api/user
Content-Type: application/json


{
    "username": "LeliaBrooks",
    "password": "password123",
    "email": "rulnonja@ak.sl@example.com",
    "fullName": "Phạm Đình Brooks",
    "provider": "google"
}
#####################
GET http://localhost:5000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5YzhkODk4MjFkYWI3OWRkZDU4MmQiLCJlbWFpbCI6InJ1bG5vbmphQGFrLnNsZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA4NjEwMTEsImV4cCI6MTczMDg2NDYxMX0.OV3k1VYgrv6b8BugoByjEahdSIO7c8UdRZtKcxN8BW8
#####################
GET http://localhost:5000/api/client/get-client/eaf766a96215dc0048e380f6dc3dac9c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5YzhkODk4MjFkYWI3OWRkZDU4MmQiLCJlbWFpbCI6InJ1bG5vbmphQGFrLnNsZXhhbXBsZS5jb20iLCJpYXQiOjE3MzEwNTYyNDQsImV4cCI6MTczMTA1OTg0NH0.7Eu5qBIIUYQK8c2GbSPt1yZhjbcNOaReGFGm7ppl6BI

#############
GET http://localhost:5000/api/user