POST http://localhost:3000/api/client/register-client
Content-Type: application/json

{
    "name":"lifetek", "redirectUri":"https://facebook.com" ,"scope":"admin", "grantTypes": "authorization_code"
}

#####################
POST http://localhost:3000/api/user
Content-Type: application/json


{
    "username": "LeliaBrooks",
    "password": "password123",
    "email": "rulnonja@ak.sl@example.com",
    "fullName": "Phạm Đình Brooks",
    "provider": "google"
}
