POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "exampleUser",
    "password": "password123",
    "email": "example@example.com",
    "fullName": "Phạm Đình Thắng",
    "provider": "google"
}

##################login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "clientId": "14605dfbdc7e01a23b3b3effc1fc070d",
    "email": "rulnonja@ak.sl@example.com",
    "password": "password123"
}
##################/oauth/token
POST http://localhost:3000/api/auth/oauth/token
Content-Type: application/json

{
    "code": "16d0e3592febd3be0aeaa5af99644d16a64e5d67"
}
##################/oauth/callback
POST http://localhost:3000/api/auth/oauth/callback
Content-Type: application/json

{
    "code": "8e4fce369e4857978813e74bef9ae64ae9d8d440"
}
##################/oauth/token
POST http://localhost:3000/api/auth/oauth/refreshToken
Content-Type: application/json

{
      "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5YzhkODk4MjFkYWI3OWRkZDU4MmQiLCJlbWFpbCI6InJ1bG5vbmphQGFrLnNsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzMwNzkzMTkwLCJleHAiOjE3MzEzOTc5OTB9.gUWQ8ZLceqFgzxUwctSpviLqq_guUsomnRIt5SALP4Q"
}

##################login
POST http://localhost:3000/api/auth/oauth/authorize
Content-Type: application/json

{
    "clientId": "d59410953cac1a6b34ff71fb0a65082e7077938c",
    "redirectUri": "http://localhost:3000/auth/oauth/callback"
}